---
title: "Project Workspace"
author: "Kayla Casey"
date: "2024-03-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
NFA_data = read.csv("NFA 2018 Edition.csv")
FAOSTAT_data = read.csv("Environment_Temperature_change_E_All_Data.csv", fileEncoding = "latin1")
head(NFA_data)
head(FAOSTAT_data)
```

```{r}
unique_countries.FAOSTAT <- unique(FAOSTAT_data$Area)
unique_countries.NFA <- unique(NFA_data$country)

common_countries <- intersect(unique_countries.FAOSTAT, unique_countries.NFA)
head(common_countries)
```

```{r}
FAOSTAT_data_subset <- FAOSTAT_data[FAOSTAT_data$Area %in% common_countries, ]
FAOSTAT_data_subset
NFA_data_subset <- NFA_data[NFA_data$country %in% common_countries, ]
NFA_data_subset
```
```{r}
largest_value <- max(NFA_data_subset$year)
largest_value
```

```{r}
numeric_cols <- c("crop_land", "grazing_land", "forest_land", "fishing_ground", "built_up_land", "carbon", "total")
NFA_data_subset[numeric_cols] <- lapply(NFA_data_subset[numeric_cols], as.numeric)

str(NFA_data_subset)

numeric_cols <- sapply(NFA_data_subset, is.numeric)
numeric_data <- NFA_data_subset[, numeric_cols]

width <- 5
height <- 4
options(repr.plot.width=width, repr.plot.height=height)

for (col in names(numeric_data)) {
    plot.new()
    
    if (any(is.finite(numeric_data[[col]]))) {
        ylim_values <- range(numeric_data[[col]], na.rm = TRUE)
    } else {
        ylim_values <- c(0, 1) 
    }
    plot.window(xlim=c(0.5, 1.5), ylim=ylim_values)
    
    boxplot(numeric_data[[col]], main=col, ylab="Value", axes=FALSE)
    
    axis(2)
    
    title(main=col)
    
    dev.print(jpeg, filename=paste0(col, ".jpeg"), width=width*100, height=height*100)
}

dev.off()

```


Time Series Work

```{r}
library(itsmr)
```


1. Time Series by World
```{r}
FAOSTAT_World_Month = read.csv("FAOSTAT_tempchg_world_month.csv")
head(FAOSTAT_World_Month)
all_months <- month.name
all_years <- 1961:2023
FAOSTAT_World_Month$Months <- factor(FAOSTAT_World_Month$Months, levels = all_months)
FAOSTAT_World_Month <- FAOSTAT_World_Month[order(FAOSTAT_World_Month$Year, as.integer(FAOSTAT_World_Month$Months)),]
print(FAOSTAT_World_Month)
FAOSTAT_World_Month_tsm = FAOSTAT_World_Month[,"Value"]
FAOSTAT_World_Month_tsm
```
```{r}
plotc(FAOSTAT_World_Month_tsm)
acf(FAOSTAT_World_Month_tsm, lag.max=40, type="correlation", plot=TRUE)
```

```{r}
xv = c("season", 12, "trend", 2)
e = Resid(FAOSTAT_World_Month_tsm, xv)
autofit(e)
plotc(e)
acf(e, lag.max=40, type="correlation", plot=TRUE)
test(e)
```
```{r}
a = arma(e, 4, 4)
f = Resid(FAOSTAT_World_Month_tsm, xv, a)
test(f)
```
```{r}
plotc(f)
```

```{r}
forecast(FAOSTAT_World_Month_tsm, xv, a, h=24, opt=2)
```







```{r}
FAOSTAT_World_Year = read.csv("FAOSTAT_tempchg_world_year.csv")
FAOSTAT_World_Year = FAOSTAT_World_Year[,"Value"]
FAOSTAT_World_Year
```

```{r}
plotc(FAOSTAT_World_Year)
acf(FAOSTAT_World_Year, lag.max=40, type="correlation", plot=TRUE)
```

```{r}
xv2 = c("season",1,"trend", 2)
e2 = Resid(FAOSTAT_World_Year, xv2)
autofit(e2)
plotc(e2)
acf(e2, lag.max=40, type="correlation", plot=TRUE)
test(e2)
```
```{r}
a2 = arma(e2, 4, 3)
f2 = Resid(FAOSTAT_World_Year, xv2, a2)
test(f2)
```
```{r}
plotc(f2)
```


```{r}
forecast(FAOSTAT_World_Year, xv2, a2, h=5, opt=2)
```







2. Time Series by Geographic Region

Africa

```{r}
FAOSTAT_Africa_Month = read.csv("FAOSTAT_tempchg_africa_month.csv")
head(FAOSTAT_Africa_Month)
all_months <- month.name
all_years <- 1961:2023
FAOSTAT_Africa_Month$Months <- factor(FAOSTAT_Africa_Month$Months, levels = all_months)
FAOSTAT_Africa_Month <- FAOSTAT_Africa_Month[order(FAOSTAT_Africa_Month$Year, as.integer(FAOSTAT_Africa_Month$Months)),]
print(FAOSTAT_Africa_Month)
FAOSTAT_Africa_Month = FAOSTAT_Africa_Month[,"Value"]
FAOSTAT_Africa_Month
```

```{r}
plotc(FAOSTAT_Africa_Month)
acf(FAOSTAT_Africa_Month, lag.max=40, type="correlation", plot=TRUE)
```

```{r}
xv3 = c("season",12,"trend", 2)
e3 = Resid(FAOSTAT_Africa_Month, xv3)
autofit(e3)
plotc(e3)
acf(e3, lag.max=40, type="correlation", plot=TRUE)
test(e3)
```
```{r}
a3 = arma(e3, 1, 1)
f3 = Resid(FAOSTAT_Africa_Month, xv3, a3)
test(f3)
```
```{r}
plotc(f3)
```


```{r}
forecast(FAOSTAT_Africa_Month, xv3, a3, h=24, opt=2)
```


Asia


Americas (South and North or both?)


Europe


Oceania
